import type { EquipeSectionProps } from './EquipeSection'

export const fixture: EquipeSectionProps = {
  number: 'Seção 5',
  title: 'Equipe do Projeto',
  subtitle: 'Critério CM-02 peso 5 — composição multidisciplinar, titulação, vínculo e dedicação',
  members: [
    {
      id: 'coord',
      avatar: '👨‍🔬',
      name: '[COORDENADOR — PREENCHER]',
      role: 'Coordenador Geral · Pesquisador Principal ([ICT EXECUTORA])',
      tags: ['IA aplicada', 'NLP / Processamento de Linguagem Natural', 'Extensão Rural Digital', 'Gestão de P&D'],
      dedication: '[X]% — mínimo exigido FINEP: 20% — PREENCHER COM DADO REAL',
      highlight: true,
    },
    {
      id: 'charles',
      avatar: '🤖',
      name: 'Charles Cleivin',
      role: 'Co-pesquisador · Arquitetura de IA e Protocolo de Validação',
      tags: ['Fine-tuning LoRA/PEFT', 'AgroEval — metodologia', 'Corpus AgroLinguaBR — curadoria', 'WhatsApp API · Backend Python', 'Next.js · TypeScript'],
      dedication: '15–20% dedicação voluntária — sem bolsa FINEP; formalizado por Termo de Colaboração com a [ICT EXECUTORA]',
      highlight: true,
      badge: 'Sem bolsa · Sem remuneração',
      badgeVariant: 'blue',
    },
    {
      id: 'dti1',
      avatar: '🎓',
      name: 'Bolsista DTI-A (a recrutar)',
      role: 'Desenvolvimento Tecnológico e Industrial — Engenharia de ML/LLM',
      tags: ['Pipeline fine-tuning', 'Avaliação AgroEval', 'Infraestrutura GPU', 'Mestrado/Doutorado em andamento'],
      dedication: '100% dedicação · Bolsa DTI-A — R$ 3.800/mês × 36 meses (incluído no orçamento)',
    },
    {
      id: 'dti2',
      avatar: '🎓',
      name: 'Bolsista DTI-B (a recrutar)',
      role: 'Desenvolvimento Tecnológico e Industrial — Engenharia de Software',
      tags: ['AgroAssistente backend', 'Coopera Digital frontend', 'AgroAPI REST', 'Superior completo'],
      dedication: '100% dedicação · Bolsa DTI-B — R$ 2.500/mês × 36 meses (incluído no orçamento)',
    },
    {
      id: 'at1',
      avatar: '🌾',
      name: 'Apoio Técnico — Agronomia (a recrutar)',
      role: 'Validação Científica do Corpus e Curadoria de Conteúdo Agrícola',
      tags: ['Agronomia', 'Curadoria AgroLinguaBR', 'Pesquisa-Ação Participativa', 'Regiões-piloto'],
      dedication: '50% dedicação · Bolsa AT — R$ 1.500/mês × 24 meses (incluído no orçamento)',
    },
    {
      id: 'thatpix',
      avatar: '🏢',
      name: 'THATPIX LTDA',
      role: 'Empresa Especializada Contratada — Engenharia e Implementação Tecnológica',
      tags: ['Fine-tuning LLM (execução técnica)', 'AgroAssistente (backend + WhatsApp)', 'Coopera Digital (frontend + backend)', 'AgroAPI (REST · auth · docs)'],
      dedication: 'R$ 46.666/mês × 36 meses — contrato de serviço PJ (não é pesquisador)',
      isPJ: true,
      badge: 'Contrato PJ · R$ 1.680.000,00',
      badgeVariant: 'amber',
    },
  ],
}
